export const ADD_MONITORING_DISPATCH_LIST_ITEM =
  "MONITORING_DISPATCH_LIST::ADD_MONITORING_DISPATCH_LIST_ITEM";
export const UPDATE_TIME_DISPATCH_CAR =
  "MONITORING_DISPATCH::UPDATE_TIME_DISPATCH_CAR";
export const ADD_INVOICE_LIST_ITEM =
  "MONITORING_DISPATCH::ADD_INVOICE_LIST_ITEM";

export const MONITORING_DISPATCH_LIST_ITEM = [
  {
    direction: "Абакан",
    numberFlight: "5311",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "7:00",
    factDeliveryTime: undefined,
    contractDeliveryTime: "3:00",
  },
  {
    direction: "Братск",
    numberFlight: "5215",
    invoices: [],
    frequencyMovement: "1,2,4,6,7",
    takeoffTime: "4:55",
    factDeliveryTime: undefined,
    contractDeliveryTime: "0:55",
  },
  {
    direction: "Благовещенск",
    numberFlight: "5211",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "23:40",
    factDeliveryTime: undefined,
    contractDeliveryTime: "19:40",
  },
  {
    direction: "Владивосток",
    numberFlight: "5203",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "23:15",
    factDeliveryTime: undefined,
    contractDeliveryTime: "19:15",
  },
  {
    direction: "Екатеринбург",
    numberFlight: "5019",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "20:00",
    factDeliveryTime: undefined,
    contractDeliveryTime: "16:00",
  },
  {
    direction: "Екатеринбург",
    numberFlight: "5017",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "14:20",
    factDeliveryTime: undefined,
    contractDeliveryTime: "10:20",
  },
  {
    direction: "Иркутск",
    numberFlight: "5227",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "2:15",
    factDeliveryTime: undefined,
    contractDeliveryTime: "22:15",
  },
  {
    direction: "Казань",
    numberFlight: "5035",
    invoices: [],
    frequencyMovement: "1,2,4,5,6,7",
    takeoffTime: "13:55",
    factDeliveryTime: undefined,
    contractDeliveryTime: "9:55",
  },
  {
    direction: "Кемерово",
    numberFlight: "5317",
    invoices: [],
    frequencyMovement: "3,5,7",
    takeoffTime: "17:20",
    factDeliveryTime: undefined,
    contractDeliveryTime: "13:20",
  },
  {
    direction: "Краснодар",
    numberFlight: "5115",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "11:25",
    factDeliveryTime: undefined,
    contractDeliveryTime: "7:25",
  },
  {
    direction: "Красноярск",
    numberFlight: "5305",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "9:00",
    factDeliveryTime: undefined,
    contractDeliveryTime: "5:00",
  },
  {
    direction: "Красноярск",
    numberFlight: "5307",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "17:45",
    factDeliveryTime: undefined,
    contractDeliveryTime: "13:45",
  },
  {
    direction: "Красноярск",
    numberFlight: "5309",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "0:55",
    factDeliveryTime: undefined,
    contractDeliveryTime: "20:55",
  },
  {
    direction: "Кызыл",
    numberFlight: "80",
    invoices: [],
    frequencyMovement: "2,6",
    takeoffTime: "13:10",
    factDeliveryTime: undefined,
    contractDeliveryTime: "9:10",
  },
  {
    direction: "Магадан",
    numberFlight: "5219",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "23:10",
    factDeliveryTime: undefined,
    contractDeliveryTime: "19:10",
  },
  {
    direction: "Мирный",
    numberFlight: "590",
    invoices: [],
    frequencyMovement: "1,3,5,6",
    takeoffTime: "3:30",
    factDeliveryTime: undefined,
    contractDeliveryTime: "23:30",
  },
  {
    direction: "Мирный",
    numberFlight: "5241",
    invoices: [],
    frequencyMovement: "1,3",
    takeoffTime: "4:10",
    factDeliveryTime: undefined,
    contractDeliveryTime: "0:10",
  },
  {
    direction: "Мирный",
    numberFlight: "5243",
    invoices: [],
    frequencyMovement: "5",
    takeoffTime: "6:30",
    factDeliveryTime: undefined,
    contractDeliveryTime: "2:30",
  },
  {
    direction: "Москва(ДМД)",
    numberFlight: "2502",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "6:25",
    factDeliveryTime: undefined,
    contractDeliveryTime: "2:25",
  },
  {
    direction: "Москва(ДМД)",
    numberFlight: "2504",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "8:40",
    factDeliveryTime: undefined,
    contractDeliveryTime: "4:40",
  },
  {
    direction: "Москва(ДМД)",
    numberFlight: "2508",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "11:55",
    factDeliveryTime: undefined,
    contractDeliveryTime: "7:55",
  },
  {
    direction: "Москва(ДМД)",
    numberFlight: "2510",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "15:20",
    factDeliveryTime: undefined,
    contractDeliveryTime: "11:20",
  },
  {
    direction: "Москва(ДМД)",
    numberFlight: "2514",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "20:40",
    factDeliveryTime: undefined,
    contractDeliveryTime: "16:40",
  },
  {
    direction: "Москва(ДМД)",
    numberFlight: "238",
    invoices: [],
    frequencyMovement: "1,4,5,6",
    takeoffTime: "9:15",
    factDeliveryTime: undefined,
    contractDeliveryTime: "5:15",
  },
  {
    direction: "Москва(ДМД)",
    numberFlight: "99",
    invoices: [],
    frequencyMovement: "1,3,6",
    takeoffTime: "8:00",
    factDeliveryTime: undefined,
    contractDeliveryTime: "4:00",
  },
  {
    direction: "Москва(ШРМ)",
    numberFlight: "1461",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "18:25",
    factDeliveryTime: undefined,
    contractDeliveryTime: "14:25",
  },
  {
    direction: "Москва(ШРМ)",
    numberFlight: "1463",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "16:20",
    factDeliveryTime: undefined,
    contractDeliveryTime: "12:20",
  },
  {
    direction: "Москва(ШРМ)",
    numberFlight: "1549",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "6:25",
    factDeliveryTime: undefined,
    contractDeliveryTime: "2:25",
  },
  {
    direction: "Москва(ШРМ)",
    numberFlight: "1307",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "10:15",
    factDeliveryTime: undefined,
    contractDeliveryTime: "6:15",
  },
  {
    direction: "Нижневартовск",
    numberFlight: "5327",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "7:15",
    factDeliveryTime: undefined,
    contractDeliveryTime: "3:15",
  },
  {
    direction: "Новый Уренгой",
    numberFlight: "5335",
    invoices: [],
    frequencyMovement: "1,2,3,4,5,7",
    takeoffTime: "13:55",
    factDeliveryTime: undefined,
    contractDeliveryTime: "9:55",
  },
  {
    direction: "Норильск",
    numberFlight: "5303",
    invoices: [],
    frequencyMovement: "1,2,3,4,5,6",
    takeoffTime: "5:10",
    factDeliveryTime: undefined,
    contractDeliveryTime: "1:10",
  },
  {
    direction: "Норильск",
    numberFlight: "916",
    invoices: [],
    frequencyMovement: "4",
    takeoffTime: "4:30",
    factDeliveryTime: undefined,
    contractDeliveryTime: "0:30",
  },
  {
    direction: "Омск",
    numberFlight: "5345",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "17:55",
    factDeliveryTime: undefined,
    contractDeliveryTime: "13:55",
  },
  {
    direction: "Пермь",
    numberFlight: "5039",
    invoices: [],
    frequencyMovement: "1,3,6",
    takeoffTime: "15:00",
    factDeliveryTime: undefined,
    contractDeliveryTime: "11:00",
  },
  {
    direction: "Пермь",
    numberFlight: "5041",
    invoices: [],
    frequencyMovement: "5",
    takeoffTime: "15:00",
    factDeliveryTime: undefined,
    contractDeliveryTime: "11:00",
  },
  {
    direction: "П.Камчатский",
    numberFlight: "5249",
    invoices: [],
    frequencyMovement: "1,2,4,5,6,7",
    takeoffTime: "23:00",
    factDeliveryTime: undefined,
    contractDeliveryTime: "19:00",
  },
  {
    direction: "Ростов-на-Дону",
    numberFlight: "5155",
    invoices: [],
    frequencyMovement: "2,5",
    takeoffTime: "12:05",
    factDeliveryTime: undefined,
    contractDeliveryTime: "8:05",
  },
  {
    direction: "Ростов-на-Дону",
    numberFlight: "220",
    invoices: [],
    frequencyMovement: "1,4,6",
    takeoffTime: "9:20",
    factDeliveryTime: undefined,
    contractDeliveryTime: "5:20",
  },
  {
    direction: "С.Петербург",
    numberFlight: "6542",
    invoices: [],
    frequencyMovement: "1,2,4,6",
    takeoffTime: "6:50",
    factDeliveryTime: undefined,
    contractDeliveryTime: "2:50",
  },
  {
    direction: "С.Петербург",
    numberFlight: "5003",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "11:25",
    factDeliveryTime: undefined,
    contractDeliveryTime: "7:25",
  },
  {
    direction: "С.Петербург",
    numberFlight: "5005",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "20:55",
    factDeliveryTime: undefined,
    contractDeliveryTime: "16:55",
  },
  {
    direction: "Симферополь",
    numberFlight: "5135",
    invoices: [],
    frequencyMovement: "3,5,7",
    takeoffTime: "10:15",
    factDeliveryTime: undefined,
    contractDeliveryTime: "6:15",
  },
  {
    direction: "Сургут",
    numberFlight: "138",
    invoices: [],
    frequencyMovement: "1,3,5,7",
    takeoffTime: "21:00",
    factDeliveryTime: undefined,
    contractDeliveryTime: "17:00",
  },
  {
    direction: "Сургут",
    numberFlight: "5347",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "12:15",
    factDeliveryTime: undefined,
    contractDeliveryTime: "8:15",
  },
  {
    direction: "Тюмень",
    numberFlight: "5351",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "14:15",
    factDeliveryTime: undefined,
    contractDeliveryTime: "10:15",
  },
  {
    direction: "Улан-Удэ",
    numberFlight: "5255",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "2:25",
    factDeliveryTime: undefined,
    contractDeliveryTime: "22:25",
  },
  {
    direction: "Уфа",
    numberFlight: "5045",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "13:05",
    factDeliveryTime: undefined,
    contractDeliveryTime: "9:05",
  },
  {
    direction: "Хабаровск",
    numberFlight: "5643",
    invoices: [],
    frequencyMovement: "1,3,5,6",
    takeoffTime: "22:55",
    factDeliveryTime: undefined,
    contractDeliveryTime: "18:55",
  },
  {
    direction: "Хабаровск",
    numberFlight: "5237",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "22:50",
    factDeliveryTime: undefined,
    contractDeliveryTime: "18:50",
  },
  {
    direction: "Челябинск",
    numberFlight: "5027",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "15:20",
    factDeliveryTime: undefined,
    contractDeliveryTime: "11:20",
  },
  {
    direction: "Чита",
    numberFlight: "5223",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "2:30",
    factDeliveryTime: undefined,
    contractDeliveryTime: "22:30",
  },
  {
    direction: "Ю.Сахалинск",
    numberFlight: "5257",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "23:00",
    factDeliveryTime: undefined,
    contractDeliveryTime: "19:00",
  },
  {
    direction: "Якутск",
    numberFlight: "5261",
    invoices: [],
    frequencyMovement: "ежд",
    takeoffTime: "23:20",
    factDeliveryTime: undefined,
    contractDeliveryTime: "19:20",
  },
  {
    direction: "Якутск",
    numberFlight: "466",
    invoices: [],
    frequencyMovement: "1",
    takeoffTime: "0:05",
    factDeliveryTime: undefined,
    contractDeliveryTime: "20:05",
  },
  {
    direction: "Якутск",
    numberFlight: "486",
    invoices: [],
    frequencyMovement: "1",
    takeoffTime: "22:00",
    factDeliveryTime: undefined,
    contractDeliveryTime: "18:00",
  },
  {
    direction: "Якутск",
    numberFlight: "486",
    invoices: [],
    frequencyMovement: "6",
    takeoffTime: "0:10",
    factDeliveryTime: undefined,
    contractDeliveryTime: "20:10",
  },
];
